/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pxu.com.views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pxu.com.connect.connecting;

/**
 *
 * @author chinh
 */
public class doimatkhau extends javax.swing.JFrame {

    /**
     * Creates new form doimatkhau
     */
    public doimatkhau() {
        initComponents();
    }

    private boolean checktk() throws SQLException, ClassNotFoundException {
        boolean kq = false;
        String sql = "select * from USERS where username=? and password=md5(?)";
        Connection conn = connecting.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txttendangnhap.getText());
        pst.setString(2, String.valueOf(mk.getPassword()));
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            return true;
        }
        return kq;
    }

    private boolean checkdoimk() {
        boolean kq = true;
        if (String.valueOf(mk.getPassword()).length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mật khẩu cũ !!!");
            return false;
        }
        if (String.valueOf(mk1.getPassword()).length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mật khẩu mới !!!");
            return false;
        }
        if (String.valueOf(mk2.getPassword()).length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập lại mật khẩu mới !!!");
            return false;
        }
        return kq;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttendangnhap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mk = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        mk1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        mk2 = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐỔI MẬT KHẨU");
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, "card2");

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.CardLayout(20, 10));

        jPanel5.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên đăng nhập:");
        jPanel5.add(jLabel2);
        jPanel5.add(txttendangnhap);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu cũ:");
        jPanel5.add(jLabel3);
        jPanel5.add(mk);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nhập mật khẩu mới:");
        jPanel5.add(jLabel4);

        mk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk1ActionPerformed(evt);
            }
        });
        jPanel5.add(mk1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nhập lại mật khẩu mới:");
        jPanel5.add(jLabel5);
        jPanel5.add(mk2);

        jPanel3.add(jPanel5, "card2");

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.CardLayout(40, 10));

        jPanel7.setLayout(new java.awt.GridLayout(1, 0, 20, 10));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 0));
        jButton1.setText("Đổi mật khẩu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 0));
        jButton2.setText("Đăng nhập");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jPanel6.add(jPanel7, "card2");

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (checkdoimk()) {
            try {
                if (checktk()) {
                    if (String.valueOf(mk1.getPassword()).equals(String.valueOf(mk2.getPassword()))) {
                        String sqlChange = "UPDATE USERS SET password=md5(?) WHERE username=N'" + txttendangnhap.getText() + "'";
                        try {
                            Connection conn = connecting.getConnection();
                            PreparedStatement pst = conn.prepareStatement(sqlChange);
                            pst.setString(1, String.valueOf(mk1.getPassword()));
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thành công !!!");
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Nhập lại mật mới khoomg chính xác !!!");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Mật mới khoomg chính xác !!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(doimatkhau.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(doimatkhau.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
//        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login h = new login();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mk1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doimatkhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField mk;
    private javax.swing.JPasswordField mk1;
    private javax.swing.JPasswordField mk2;
    private javax.swing.JTextField txttendangnhap;
    // End of variables declaration//GEN-END:variables
}
